version: "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./planner-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/plannerApp
    depends_on:
      - mongodb
